name: Setup
description: 'Setup stuff'
runs:
  using: "composite"
  steps:
    - name: set up JDK 21
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
