name: Setup
description: 'Setup stuff'
runs:
  using: "composite"
  steps:
    - name: set up JDK 20
      uses: actions/setup-java@v4.1.0
      with:
        distribution: 'zulu'
        java-version: '20'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.1.0
