# Copyright (C) 2026 Nicholas Doglio
# SPDX-License-Identifier: MIT

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
