[versions]
min-sdk = "24"
target-sdk = "33"
compile-sdk = "33"
agp = "8.0.1"
jacoco = "0.8.8"
kotlin = "1.8.10"
detekt = "1.22.0"
coroutines = "1.7.0"
retrofit = "2.9.0"
okhttp = "4.11.0"
composeCompiler = "1.4.2"
dagger = "2.45"
moshi = "1.14.0"
work = "2.8.1"
glanceTool = "0.2.2"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version = "0.8.1" }
play-publish = { id = "com.github.triplet.play", version = "3.8.2" }
junit-jacoco = { id = "com.vanniktech.android.junit.jacoco", version = "0.16.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }
android-app = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
moshiIr = { id = "dev.zacsweers.moshix", version = "0.21.0" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.46.0" }
anvil = { id = "com.squareup.anvil", version = "2.4.4" }
tangle = { id = "com.rickbusarow.tangle", version = "0.15.1" }
paparazzi = { id = "app.cash.paparazzi", version = "1.2.0" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version = "0.12.0" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.10.0" }
androidx-datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }
androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.1" }
androidx-material = { module = "com.google.android.material:material", version = "1.8.0" }

compose-bom = { module = "androidx.compose:compose-bom", version = "2023.05.00" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-material = { module = "androidx.compose.material3:material3" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version = "1.0.0-alpha05" }
glanceTool-configuration = { module = "com.google.android.glance.tools:appwidget-configuration", version.ref = "glanceTool" }
glanceTool-viewer = { module = "com.google.android.glance.tools:appwidget-viewer", version.ref = "glanceTool" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }

eithernet = { module = "com.slack.eithernet:eithernet", version = "1.3.1" }
desguar = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.3" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

lints-compose = { module = "com.slack.lint.compose:compose-lint-checks", version = "1.2.0" }

junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
androidx-workmanager-test = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
