[versions]
min-sdk = "24"
target-sdk = "33"
compile-sdk = "33"
agp = "7.2.2"
kotlin = "1.7.10"
detekt = "1.21.0"
coroutines = "1.6.4"
retrofit = "2.9.0"
okhttp = "4.10.0"
compose = "1.2.1"
composeCompiler = "1.3.0-beta01"
dagger = "2.43.2"
moshi = "1.14.0"
work = "2.8.0-alpha03"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version = "0.8.1" }
play-publish = { id = "com.github.triplet.play", version = "3.7.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.13.1" }
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
moshiIr = { id = "dev.zacsweers.moshix", version = "0.18.3" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
anvil = { id = "com.squareup.anvil", version = "2.4.2" }
tangle = { id = "com.rickbusarow.tangle", version = "0.15.1" }
paparazzi = { id = "app.cash.paparazzi", version = "1.0.0" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.8.0" }
androidx-datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }
androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.5.1" }
androidx-material = { module = "com.google.android.material:material", version = "1.6.1" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-material = { module = "androidx.compose.material3:material3", version = "1.0.0-beta02" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version = "1.0.0-alpha04" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

eithernet = { module = "com.slack.eithernet:eithernet", version = "1.2.1" }
desguar = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.6" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
androidx-workmanager-test = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
compose-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
