
[versions]
agp = "7.1.2"
kotlin = "1.6.10"
detekt = "1.19.0"
coroutines = "1.6.0"
retrofit = "2.9.0"
compose = "1.2.0-alpha06"
dagger = "2.41"
moshi = "1.13.0"
work = "2.8.0-alpha01"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version = "0.8.0" }
play-publish = { id = "com.github.triplet.play", version = "3.7.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.0.0-rc05" }
android-app = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.6.10-1.0.4" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
anvil = { id = "com.squareup.anvil", version = "2.4.0" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0-alpha02" }
androidx-datastore = { module = "androidx.datastore:datastore", version = "1.0.0" }
androidx-workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-workmanager-test = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.6.0-alpha01" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

dagger-core = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-ksp = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

eithernet = { module = "com.slack.eithernet:eithernet", version = "1.2.1" }

junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.8.1" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha08" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version = "1.0.0-alpha03" }

