name: CI
on: [ push ]
jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./.github/actions/setup
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.3.2
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./.github/actions/setup
      - name: Build Debug APK
        run: ./gradlew assembleDebug
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detektMain, detektTest, lint, spotlessCheck, checkSortDependencies, licensee ]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
