name: CI
on: [ push ]
jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2.1.2
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup
      - name: Build Debug APK
        run: ./gradlew assembleDebug
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detekt, lint, spotlessCheck, checkSortDependencies, licensee ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
