name: CI
on: [ push ]
jobs:
  Validate-Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: ./.github/actions/setup
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3.3.2
  Build:
    runs-on: ubuntu-latest
    needs: [ Validate-Gradle ]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: ./.github/actions/setup
      - name: Build Debug APK
        run: ./gradlew assembleDebug
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    strategy:
      matrix:
        command: [ detekt, lint, spotlessCheck, checkSortDependencies, licensee ]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: ./.github/actions/setup
      - name: Lint
        run: ./gradlew ${{ matrix.command }}
  Tests:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Codecov
        uses: codecov/codecov-action@v4.3.1
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
